[package]
name = "debug_lru_direct_test"
version = "0.1.0"
edition = "2021"

[workspace]

[[bin]]
name = "debug_lru_direct_test"
path = "debug_lru_direct_test.rs"

[[bin]]
name = "debug_lru_actual_limit"
path = "../debug_lru_actual_limit.rs"

[dependencies]
lru-mem = "0.2.0"