[workspace]
resolver = "2"
members = [
  "runtime",
  "memshrew",
  "metashrew-core",
  "metashrew-support",
  "memshrew-p2p",
  "rockshrew-diff",
  "metashrew-minimal",
  "memshrew-store",
  "metashrew-test-harness",
  "crates/metashrew-smt-trait",
  "crates/metashrew-rocksdb",
  "crates/rockshrew",
  "src"
]
