[package]
name = "rockshrew-runtime"
version = "9.0.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
log = "0.4.22"
rocksdb = { version = "0.21.0", features = ["multi-threaded-cf"] }
metashrew-runtime = { path = "../metashrew-runtime" }

[dev-dependencies]
tempfile = "3.8.1"