[package]
name = "rockshrew"
version = "0.1.0"
edition = "2021"
description = "Combined indexer and view layer for Metashrew"
license = "MIT"

[dependencies]
metashrew-runtime = { path = "../../runtime" }
metashrew-rocksdb = { path = "../metashrew-rocksdb" }
rockshrew-smt = { path = "../rockshrew-smt" }
actix-cors = "0.6"
actix-web = "4.5"
anyhow = "1.0"
bytes = "1.5"
clap = { version = "4.5", features = ["derive"] }
dirs = "5.0"
env_logger = "0.10"
hex = "0.4"
log = "0.4"
num_cpus = "1.16"
once_cell = "1.19"
rand = "0.8"
reqwest = { version = "0.11", features = ["json"] }
rocksdb = "0.21.0"
russh = "0.50.0-beta.7"
russh-keys = "0.38.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha2 = "0.10"
tokio = { version = "1.43", features = ["full"] }
url = "2.5"
zstd = "0.13"