[package]
name = "rockshrew"
version = "0.1.0"
edition = "2021"
description = "Combined indexer and view layer for Metashrew"
license = "MIT"

[dependencies]
metashrew-runtime = { path = "../../runtime" }
metashrew-rocksdb = { path = "../metashrew-rocksdb" }
metashrew-smt-trait = { path = "../metashrew-smt-trait" }
actix-cors = "0.6"
actix-web = "4.5"
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
env_logger = "0.10"
hex = "0.4"
log = "0.4"
num_cpus = "1.16"
rand = "0.8"
rocksdb = "0.21.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.43", features = ["full"] }