[package]
name = "metashrew-println"
version.workspace = true
edition = "2021"

[dependencies]
wasm-bindgen = { version = "0.2.100", optional = true }

[features]
wasm = []
test-utils = ["wasm-bindgen"]
