[package]
name = "memshrew-store"
version = "9.0.0"
edition = "2024"

[dependencies]
metashrew-runtime = { path = "../runtime" }
metashrew-smt-trait = { path = "../crates/metashrew-smt-trait" }
async-trait = "0.1.81"
anyhow = "1.0.86"
sha2 = "0.10"
hex = "0.4"
