[package]
name = "memshrew-runtime"
version = "9.0.0"
edition = "2021"

[dependencies]
metashrew-runtime = { path = "../metashrew-runtime" }
anyhow = "1.0.86"
log = "0.4.22"

[dev-dependencies]
tempfile = "3.8.1"
